// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Action    string
	TargetID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Capsule struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Title     string
	Purpose   string
	Summary   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CapsuleClaim struct {
	ProjectID  pgtype.UUID
	CapsuleID  pgtype.UUID
	ClaimID    pgtype.UUID
	OrderIndex int32
}

type Claim struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	SourceID        pgtype.UUID
	SourceVersionID pgtype.UUID
	ClaimType       string
	Content         string
	Status          string
	VerifiedByUser  bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Packet struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	CapsuleID       pgtype.UUID
	TargetProfileID string
	Title           string
	Body            string
	RedactionCount  int32
	TokenEstimate   int32
	CreatedAt       pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description string
	ProjectType string
	Objective   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Source struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	SourceType string
	Title      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SourceVersion struct {
	ID          pgtype.UUID
	SourceID    pgtype.UUID
	Version     int32
	ArtifactUri string
	ContentHash string
	ByteSize    int64
	CreatedAt   pgtype.Timestamptz
}

type WcefRun struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	CaseID            string
	ReportArtifactUri string
	ScoresArtifactUri string
	CreatedAt         pgtype.Timestamptz
}
