// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClaimToCapsule = `-- name: AddClaimToCapsule :exec
INSERT INTO capsule_claims (project_id, capsule_id, claim_id, order_index)
VALUES ($1, $2, $3, $4)
`

type AddClaimToCapsuleParams struct {
	ProjectID  pgtype.UUID
	CapsuleID  pgtype.UUID
	ClaimID    pgtype.UUID
	OrderIndex int32
}

func (q *Queries) AddClaimToCapsule(ctx context.Context, arg AddClaimToCapsuleParams) error {
	_, err := q.db.Exec(ctx, addClaimToCapsule,
		arg.ProjectID,
		arg.CapsuleID,
		arg.ClaimID,
		arg.OrderIndex,
	)
	return err
}

const confirmClaim = `-- name: ConfirmClaim :one
UPDATE claims
SET status = 'confirmed', verified_by_user = true, updated_at = now()
WHERE id = $1
RETURNING id, project_id, source_id, source_version_id, claim_type, content, status, verified_by_user, created_at, updated_at
`

func (q *Queries) ConfirmClaim(ctx context.Context, id pgtype.UUID) (Claim, error) {
	row := q.db.QueryRow(ctx, confirmClaim, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.SourceVersionID,
		&i.ClaimType,
		&i.Content,
		&i.Status,
		&i.VerifiedByUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (project_id, action, target_id)
VALUES ($1, $2, $3)
RETURNING id, project_id, action, target_id, created_at
`

type CreateAuditLogParams struct {
	ProjectID pgtype.UUID
	Action    string
	TargetID  pgtype.UUID
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog, arg.ProjectID, arg.Action, arg.TargetID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Action,
		&i.TargetID,
		&i.CreatedAt,
	)
	return i, err
}

const createCapsule = `-- name: CreateCapsule :one
INSERT INTO capsules (project_id, title, purpose, summary)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, purpose, summary, created_at, updated_at
`

type CreateCapsuleParams struct {
	ProjectID pgtype.UUID
	Title     string
	Purpose   string
	Summary   string
}

func (q *Queries) CreateCapsule(ctx context.Context, arg CreateCapsuleParams) (Capsule, error) {
	row := q.db.QueryRow(ctx, createCapsule,
		arg.ProjectID,
		arg.Title,
		arg.Purpose,
		arg.Summary,
	)
	var i Capsule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Purpose,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (project_id, source_id, source_version_id, claim_type, content, status, verified_by_user)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, source_id, source_version_id, claim_type, content, status, verified_by_user, created_at, updated_at
`

type CreateClaimParams struct {
	ProjectID       pgtype.UUID
	SourceID        pgtype.UUID
	SourceVersionID pgtype.UUID
	ClaimType       string
	Content         string
	Status          string
	VerifiedByUser  bool
}

func (q *Queries) CreateClaim(ctx context.Context, arg CreateClaimParams) (Claim, error) {
	row := q.db.QueryRow(ctx, createClaim,
		arg.ProjectID,
		arg.SourceID,
		arg.SourceVersionID,
		arg.ClaimType,
		arg.Content,
		arg.Status,
		arg.VerifiedByUser,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.SourceVersionID,
		&i.ClaimType,
		&i.Content,
		&i.Status,
		&i.VerifiedByUser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPacket = `-- name: CreatePacket :one
INSERT INTO packets (project_id, capsule_id, target_profile_id, title, body, redaction_count, token_estimate)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, capsule_id, target_profile_id, title, body, redaction_count, token_estimate, created_at
`

type CreatePacketParams struct {
	ProjectID       pgtype.UUID
	CapsuleID       pgtype.UUID
	TargetProfileID string
	Title           string
	Body            string
	RedactionCount  int32
	TokenEstimate   int32
}

func (q *Queries) CreatePacket(ctx context.Context, arg CreatePacketParams) (Packet, error) {
	row := q.db.QueryRow(ctx, createPacket,
		arg.ProjectID,
		arg.CapsuleID,
		arg.TargetProfileID,
		arg.Title,
		arg.Body,
		arg.RedactionCount,
		arg.TokenEstimate,
	)
	var i Packet
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CapsuleID,
		&i.TargetProfileID,
		&i.Title,
		&i.Body,
		&i.RedactionCount,
		&i.TokenEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, project_type, objective)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, project_type, objective, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string
	Description string
	ProjectType string
	Objective   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.ProjectType,
		arg.Objective,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ProjectType,
		&i.Objective,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSource = `-- name: CreateSource :one
INSERT INTO sources (project_id, source_type, title)
VALUES ($1, $2, $3)
RETURNING id, project_id, source_type, title, created_at, updated_at
`

type CreateSourceParams struct {
	ProjectID  pgtype.UUID
	SourceType string
	Title      string
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, createSource, arg.ProjectID, arg.SourceType, arg.Title)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceType,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSourceVersion = `-- name: CreateSourceVersion :one
INSERT INTO source_versions (source_id, version, artifact_uri, content_hash, byte_size)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, source_id, version, artifact_uri, content_hash, byte_size, created_at
`

type CreateSourceVersionParams struct {
	SourceID    pgtype.UUID
	Version     int32
	ArtifactUri string
	ContentHash string
	ByteSize    int64
}

func (q *Queries) CreateSourceVersion(ctx context.Context, arg CreateSourceVersionParams) (SourceVersion, error) {
	row := q.db.QueryRow(ctx, createSourceVersion,
		arg.SourceID,
		arg.Version,
		arg.ArtifactUri,
		arg.ContentHash,
		arg.ByteSize,
	)
	var i SourceVersion
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Version,
		&i.ArtifactUri,
		&i.ContentHash,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const createWCEFRun = `-- name: CreateWCEFRun :one
INSERT INTO wcef_runs (project_id, case_id, report_artifact_uri, scores_artifact_uri)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, case_id, report_artifact_uri, scores_artifact_uri, created_at
`

type CreateWCEFRunParams struct {
	ProjectID         pgtype.UUID
	CaseID            string
	ReportArtifactUri string
	ScoresArtifactUri string
}

func (q *Queries) CreateWCEFRun(ctx context.Context, arg CreateWCEFRunParams) (WcefRun, error) {
	row := q.db.QueryRow(ctx, createWCEFRun,
		arg.ProjectID,
		arg.CaseID,
		arg.ReportArtifactUri,
		arg.ScoresArtifactUri,
	)
	var i WcefRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CaseID,
		&i.ReportArtifactUri,
		&i.ScoresArtifactUri,
		&i.CreatedAt,
	)
	return i, err
}

const listConfirmedClaimsByProject = `-- name: ListConfirmedClaimsByProject :many
SELECT id, project_id, source_id, source_version_id, claim_type, content, status, verified_by_user, created_at, updated_at
FROM claims
WHERE project_id = $1 AND status IN ('confirmed', 'active') AND verified_by_user = true
ORDER BY created_at, id
`

func (q *Queries) ListConfirmedClaimsByProject(ctx context.Context, projectID pgtype.UUID) ([]Claim, error) {
	rows, err := q.db.Query(ctx, listConfirmedClaimsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Claim
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.SourceVersionID,
			&i.ClaimType,
			&i.Content,
			&i.Status,
			&i.VerifiedByUser,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
